using System;
using System.Collections.Concurrent;
using System.IO;
using System.Net;
using System.Text;
using System.Reflection;
using System.Runtime.InteropServices;
using BepInEx;
using BepInEx.Unity.IL2CPP;
using HarmonyLib;
using TMPro;

namespace SuzerainAltTFix
{
    [BepInPlugin("com.asciihorse.suzerainmod.2500plus", "Suzerain IL2CPP (2500+ characters, but Alt+T not working properly)", "1.0.1")]
    public class Plugin : BasePlugin
    {
        public static readonly ConcurrentDictionary<int, string> OriginalEnglishStore = new ConcurrentDictionary<int, string>();
        public static readonly ConcurrentDictionary<int, string> TranslatedUkrainianStore = new ConcurrentDictionary<int, string>();

        // Weak reference to large component (Code) to avoid memory leak in IL2CPP
        public static readonly WeakReference<TMP_Text> LastLongTextComponent = new WeakReference<TMP_Text>(null);

        public static bool TranslationsEnabled = true;
        public static string XUnityCachePath;

        [DllImport("user32.dll")]
        public static extern short GetAsyncKeyState(int vKey);

        public override void Load()
        {
            XUnityCachePath = Path.Combine(Paths.GameRootPath, "BepInEx", "Translation", "uk", "Text", "_AutoGeneratedTranslations.txt");

            var harmony = new Harmony("com.asciihorse.suzerainmod.2500plus");
            harmony.PatchAll();

            // Dynamically lookup XUnity proxy class to synchronize keyboard update cycle
            try
            {
                MethodInfo updateMethod = null;
                foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
                {
                    var type = assembly.GetType("XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour");
                    if (type != null)
                    {
                        updateMethod = type.GetMethod("Update", BindingFlags.Public | BindingFlags.Instance | BindingFlags.NonPublic);
                        if (updateMethod != null) break;
                    }
                }

                if (updateMethod != null)
                {
                    var postfix = new HarmonyMethod(typeof(Plugin).GetMethod(nameof(XUnity_Update_Postfix), BindingFlags.Static | BindingFlags.Public));
                    harmony.Patch(updateMethod, postfix: postfix);
                    Log.LogInfo("[Fix] Safely synchronized with XUnity Update loop.");
                }
            }
            catch (Exception ex)
            {
                Log.LogWarning("[Fix] Non-critical: Failed to hook XUnity Update: " + ex.Message);
            }

            Log.LogInfo("=== [Fix] Text-Getter hook via InstanceID activated successfully! ===");
        }

        // Checking Alt (0x12) + T (0x54) keystrokes directly through Windows
        private static bool _wasPressed = false;
        public static void XUnity_Update_Postfix()
        {
            bool isAltDown = (GetAsyncKeyState(0x12) & 0x8000) != 0;
            bool isTDown = (GetAsyncKeyState(0x54) & 0x8000) != 0;
            bool isCurrentlyPressed = isAltDown && isTDown;

            if (isCurrentlyPressed && !_wasPressed)
            {
                TranslationsEnabled = !TranslationsEnabled;

                // Trying to switch language for large text on the screen (NOT WORKING)
                if (LastLongTextComponent.TryGetTarget(out var tmpText) && tmpText != null)
                {
                    if (TranslationsEnabled && TranslatedUkrainianStore.TryGetValue(tmpText.GetInstanceID(), out string ukrText))
                    {
                        tmpText.text = ukrText;
                    }
                    else if (!TranslationsEnabled && OriginalEnglishStore.TryGetValue(tmpText.GetInstanceID(), out string engText))
                    {
                        tmpText.text = engText;
                    }
                }
            }
            _wasPressed = isCurrentlyPressed;
        }

        public static bool ContainsCyrillic(string text)
        {
            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                if (c >= 0x0400 && c <= 0x04FF) return true;
            }
            return false;
        }
    }

    [HarmonyPatch(typeof(TMP_Text), nameof(TMP_Text.text), MethodType.Setter)]
    public static class TMP_Text_Setter_Patch
    {
        [HarmonyPrefix]
        public static void Prefix(TMP_Text __instance, ref string value)
        {
            if (__instance == null || string.IsNullOrEmpty(value)) return;

            if (!Plugin.ContainsCyrillic(value))
            {
                Plugin.OriginalEnglishStore[__instance.GetInstanceID()] = value;

                // bypassing the limit: if text > 2200 -> we translate
                if (value.Length > 2200)
                {
                    Plugin.LastLongTextComponent.SetTarget(__instance);

                    if (Plugin.TranslationsEnabled)
                    {
                        string translated = SendToPythonBridge(value);
                        if (!string.IsNullOrEmpty(translated))
                        {
                            Plugin.TranslatedUkrainianStore[__instance.GetInstanceID()] = translated;
                            SaveToXUnityFile(value, translated);
                            value = translated; // Changing to ukrainian
                            return;
                        }
                    }
                }
            }
        }

        private static string SendToPythonBridge(string text)
        {
            try
            {
                var request = (HttpWebRequest)WebRequest.Create("http://localhost:8500/");
                request.Method = "POST";
                request.ContentType = "text/plain; charset=utf-8";
                request.Timeout = 5000;

                byte[] bytes = Encoding.UTF8.GetBytes(text);
                request.ContentLength = bytes.Length;

                using (var stream = request.GetRequestStream())
                {
                    stream.Write(bytes, 0, bytes.Length);
                }

                using (var response = (HttpWebResponse)request.GetResponse())
                using (var reader = new StreamReader(response.GetResponseStream(), Encoding.UTF8))
                {
                    return reader.ReadToEnd();
                }
            }
            catch { return null; }
        }

        private static void SaveToXUnityFile(string english, string ukrainian)
        {
            try
            {
                string dir = Path.GetDirectoryName(Plugin.XUnityCachePath);
                if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

                string engLine = english.Replace("\r", "").Replace("\n", "\\n");
                string ukrLine = ukrainian.Replace("\r", "").Replace("\n", "\\n");
                string row = $"{engLine}={ukrLine}\n";

                if (File.Exists(Plugin.XUnityCachePath))
                {
                    string content = File.ReadAllText(Plugin.XUnityCachePath);
                    if (content.Contains(engLine + "=")) return;
                }

                File.AppendAllText(Plugin.XUnityCachePath, row, Encoding.UTF8);
            }
            catch { }
        }
    }

    [HarmonyPatch(typeof(TMP_Text), nameof(TMP_Text.text), MethodType.Getter)]
    public static class TMP_Text_Getter_Patch
    {
        [HarmonyPrefix]
        public static bool Prefix(TMP_Text __instance, ref string __result)
        {
            if (__instance == null) return true;

            if (Plugin.OriginalEnglishStore.TryGetValue(__instance.GetInstanceID(), out string originalEnglish))
            {
                // For long Codex texts, let the game read the current state without forcing a rollback
                if (originalEnglish.Length > 2000) return true;

                __result = originalEnglish;
                return false;
            }
            return true;
        }
    }
}
