<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\interop\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="XUnity.AutoTranslator.Plugin.Core">
      <HintPath>..\..\..\Program Files (x86)\Steam\steamapps\common\Suzerain\BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
